version: '3'

services:
  php:
    image: lvinkim/php-env-docker:latest
    ports:
      - 8080:8080
    volumes:
      - .:/var/www/html
      - ./xdebug.disable.ini:/etc/php/7.2/mods-available/xdebug.ini
    working_dir: /var/www/html
    command:
      - php
      - bin/server.php
      - swoole:start
